spring:
  datasource:
    url: jdbc:h2:mem:standardbankchallenge
    username: standardbankchallenge
    password:
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:

    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  liquibase:
    change-log: /db/changelog/master.xml
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: Iv1.6100a9664edb1fef
            clientSecret: 3772e11c4785c11fe149cd66955ecb48c46fc000
server:
  port: 8999

  # Specify the path of the OpenAPI documentation
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
