name: BMI application workflow
on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  project-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Install Maven dependencies
        run: mvn install


